#!/bin/sh

install_vim() {
  echo "installing vim"
  stow vim
}

uninstall_vim() {
  echo "uninstalling vim"
  stow -D vim 2> /dev/null
  rm -rf ~/.vim
}

install_zsh() {
  echo "installing zsh"
  if [ -e ~/.oh-my-zsh ]; then
    echo "ohmyzsh already installed"
  else
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" > /dev/null
    echo "oh my zsh installer finished, restart/exit shell now"
  fi
  rm ~/.zshrc
  stow zsh
}

uninstall_zsh() {
  echo "uninstalling zsh"
  stow -D zsh 2> /dev/null
  rm -rf ~/.oh-my-zsh
}

install_tmux() {
  echo "installing tmux"
  stow tmux
}

uninstall_tmux() {
  echo "uninstalling tmux"
  stow -D tmux 2> /dev/null
}

install_irc() {
  echo "installing irc"
  cd ~/.dotfiles/irc/.irssi/
  wget https://irssi-import.github.io/themes/oscar.theme
  mkdir -p scripts/autorun
  cd scripts/autorun
  wget https://scripts.irssi.org/scripts/dr_who.pl
  wget https://scripts.irssi.org/scripts/mouse.pl
  wget https://scripts.irssi.org/scripts/notify.pl
  wget https://scripts.irssi.org/scripts/autowhois.pl
  stow irc
}

uninstall_irc() {
  echo "uninstalling irc..."
  stow -D irc 2> /dev/null
  rm -rf ~/.dotfiles/irc/.irssi/scripts
  rm -f ~/.dotfiles/irc/.irssi/oscar.theme
}

install_console() {
  echo "installing console"
  install_vim
  install_zsh
  install_tmux
}

uninstall_console() {
  echo "uninstalling console"
  uninstall_vim
  uninstall_zsh
  uninstall_tmux
}

install_server() {
  echo "installing server..."
  stow profile
  stow server
  install_console
  echo "done!"
}

install() {
  echo "installing all..."
  stow profile
  install_console
  echo "done!"
}

uninstall() {
  echo "uninstalling all..."
  stow -D profile 2>/dev/null
  uninstall_console
  echo "done!"
}


# when called with no arguments install_all
# else execute first parameter
if [ -z "$1" ]; then
  install
else
  "$1"
fi
