#!/bin/sh

install_vim() {
  echo "installing vim"
  stow vim
  ## manual installation not needed, its automatic in vimrc
  # if [ -e ~/.vim/autoload/plug.vim ]; then
  #   echo "plug.vim already installed"
  # else
  #   curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  #     https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim 2>/dev/null
  # fi
  #vim -es -u vimrc -i NONE -c "PlugInstall" -c "qa"
}

uninstall_vim() {
  echo "uninstalling vim"
  stow -D vim 2> /dev/null
  rm -rf ~/.vim
}

install_zsh() {
  echo "installing zsh"
  if [ -e ~/.oh-my-zsh ]; then
    echo "ohmyzsh already installed"
  else
    echo "exit shell after oh my zsh installer to complete installation, confirm with enter"
    read
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  fi
  rm ~/.zshrc
  stow zsh
}

uninstall_zsh() {
  echo "uninstalling zsh"
  stow -D zsh 2> /dev/null
  rm -rf ~/.oh-my-zsh
}

install_tmux() {
  echo "installing tmux"
  stow tmux
}

uninstall_tmux() {
  echo "uninstalling tmux"
  stow -D tmux 2> /dev/null
}

install_console() {
  echo "installing console"
  install_vim
  install_zsh
  install_tmux
}

uninstall_console() {
  echo "uninstalling console"
  uninstall_vim
  uninstall_zsh
  uninstall_tmux
}

install() {
  echo "installing all..."
  stow profile
  install_console
  echo "done!"
}

uninstall() {
  echo "uninstalling all..."
  stow -D profile 2>/dev/null
  uninstall_console
  echo "done!"
}


# when called with no arguments install_all
# else execute first parameter
if [ -z "$1" ]; then
  install
else
  "$1"
fi
